<?php

return [
    [
        'label' => 'Dashboard',
        'route' => 'dashboard',
        'icon' => 'home',
        'roles' => ['admin', 'store_manager', 'cashier', 'site_manager'],
    ],
    [
        'label' => 'Shop',
        'type' => 'heading',
        'roles' => ['admin', 'store_manager', 'cashier'],
    ],
    [
        'label' => 'Products',
        'route' => 'store.products.index',
        'active' => ['store.products.*', 'store.categories.*', 'store.brands.*', 'store.units.*'],
        'icon' => 'cube',
        'roles' => ['admin', 'store_manager'],
    ],
    [
        'label' => 'Suppliers',
        'route' => 'store.suppliers.index',
        'active' => 'store.suppliers.*',
        'icon' => 'users',
        'roles' => ['admin', 'store_manager'],
    ],
    [
        'label' => 'Purchases',
        'route' => 'store.purchases.index',
        'active' => 'store.purchases.*',
        'icon' => 'truck',
        'roles' => ['admin', 'store_manager'],
    ],
    [
        'label' => 'Inventory',
        'route' => 'store.inventory.index',
        'active' => 'store.inventory.*',
        'icon' => 'archive',
        'roles' => ['admin', 'store_manager'],
    ],
    [
        'label' => 'Sales',
        'route' => 'store.sales.index',
        'active' => 'store.sales.*',
        'icon' => 'shopping-cart',
        'roles' => ['admin', 'store_manager', 'cashier'],
    ],
    [
        'label' => 'Customers',
        'route' => 'store.customers.index',
        'active' => 'store.customers.*',
        'icon' => 'users',
        'roles' => ['admin', 'store_manager', 'cashier'],
    ],
    [
        'label' => 'Material Requests',
        'route' => 'store.material-requests.index',
        'active' => ['store.material-requests.*', 'store.material-issues.*'],
        'icon' => 'clipboard',
        'roles' => ['admin', 'store_manager'],
    ],
    [
        'label' => 'Construction',
        'type' => 'heading',
        'roles' => ['admin', 'site_manager'],
    ],
    [
        'label' => 'Projects',
        'route' => 'construction.projects.index',
        'active' => 'construction.projects.*',
        'icon' => 'building',
        'roles' => ['admin', 'site_manager'],
    ],
    [
        'label' => 'Workers',
        'route' => 'construction.workers.index',
        'active' => 'construction.workers.*',
        'icon' => 'hard-hat',
        'roles' => ['admin', 'site_manager'],
    ],
    [
        'label' => 'My Requests',
        'route' => 'construction.material-requests.index',
        'active' => 'construction.material-requests.*',
        'icon' => 'inbox',
        'roles' => ['admin', 'site_manager'],
    ],
    [
        'label' => 'Reports',
        'type' => 'heading',
        'roles' => ['admin', 'store_manager', 'site_manager'],
    ],
    [
        'label' => 'Reports',
        'route' => 'reports.index',
        'active' => 'reports.*',
        'icon' => 'chart-bar',
        'roles' => ['admin', 'store_manager', 'site_manager'],
    ],
    [
        'label' => 'System',
        'type' => 'heading',
        'roles' => ['admin'],
    ],
    [
        'label' => 'Users',
        'route' => 'admin.users.index',
        'active' => 'admin.users.*',
        'icon' => 'user-cog',
        'roles' => ['admin'],
    ],
    [
        'label' => 'Activity Logs',
        'route' => 'admin.activity-logs.index',
        'active' => 'admin.activity-logs.*',
        'icon' => 'clipboard',
        'roles' => ['admin'],
    ],
    [
        'label' => 'SMS Logs',
        'route' => 'admin.sms-logs.index',
        'active' => 'admin.sms-logs.*',
        'icon' => 'clipboard',
        'roles' => ['admin'],
    ],
    [
        'label' => 'Settings',
        'route' => 'admin.settings.edit',
        'active' => 'admin.settings.*',
        'icon' => 'cog',
        'roles' => ['admin'],
    ],
];
